'use strict';


const STRINGS = {
  es: {
    title: 'MATRIX HACK TERMINAL v1.0',
    headerPrompt: 'root@matrix:~$',
    handle: '>> NEO_001',
    level: 'NIVEL: {n}',
    mb: 'MB',
    btnPrompt: '[root@matrix]~$',
    btnText: './hack.exe',
    secure: '[CONEXIÓN SEGURA]',
    autoSave: 'AUTO-GUARDADO ACTIVO',
    saved: 'GUARDADO {time}',
    offline: 'OFFLINE +{n}',
    synergyDivider: ' | ',
    synergyScanner: 'SCANNER→CPU +{n} DPS',
    synergyArch: 'ARQUITECTO x{n}',
    critText: '¡CRÍTICO! x3',
    autoPrefix: '[AUTO]',
    panelTitle: '> MEJORAS_',
    buyModeLabel: 'COMPRAR:',
    buyMax: 'MAX',
    autoBuyOn: 'AUTO: ON',
    autoBuyOff: 'AUTO: OFF',
    achBtn: 'LOGROS',
    statsBtn: 'ESTADÍSTICAS',
    skinBtn: 'PIELES',
    prestigeShopBtn: '◆ TIENDA',
    exportBtn: '↑ EXPORT',
    importBtn: '↓ IMPORT',
    groupClick: '> CLICK_',
    groupDps: '> DPS_',
    groupSpecial: '> ESPECIAL_',
    groupMult: '> MULTIPLICADORES_',
    milestoneLabel: '{n}',
    upgradeCount: '{n}/{m}',
    cardLvl: 'NVL',
    effectClick: 'CLICK +{n}',
    effectDps: 'DPS +{n}',
    effectCrit: '{n}% CRIT',
    effectDiscount: '-{n}% COSTO',
    effectAutoclick: '{n} click/8s',
    effectMultClick: 'CLICK x{n}',
    effectMultDps: 'DPS x{n}',
    effectOffline: '{n}% OFFLINE',
    effectClickDps: 'CLICK/DPS +{n}',
    effectCritDmg: 'CRIT x{n}',
    effectAutoSpeed: '-{n}ms AUTO',
    effectComboBoost: '+{n} COMBO',
    synergyBtn: 'SINERGIAS',
    synergyTitle: '> SINERGIAS_',
    synergyScannerName: 'Scanner→CPU',
    synergyArchName: 'Arquitecto',
    synergyReqs: 'Requisitos:',
    synergyEffect: 'Efecto:',
    synergyUnlocked: '✓ DESBLOQUEADA',
    synergyUnknown: '??',
    synergyScannerReqs: ['Scanner NVL 5+', 'CPU NVL 1+'],
    synergyScannerEffect: 'DPS +{n}',
    synergyArchLabel: '1 mejora en NVL 10+',
    synergyArchEffect: 'DPS x{n}',
    synergyOverdriveName: 'Sobrecarga',
    synergyOverdriveEffect: 'CLICK x1.5',
    synergyCipherName: 'Llave Maestra',
    synergyCipherEffect: 'DPS x2',
    synergyComboName: 'Flujo Continuo',
    synergyComboEffect: 'COMBO MAX +10',
    synergyMetaName: 'Desbordamiento',
    synergyMetaEffect: '-5% COSTO',
    groupCombo: '> COMBO_',
    groupMeta: '> META_',
    statClick: 'CLICK',
    statDps: 'DPS',
    statCrit: 'CRIT',
    statDiscount: 'DTO',
    unitPercent: '%',
    offlineExtra: ' GANADOS',
    resetConfirm: '¿Reiniciar todos los datos del juego?',
    prestigeLabel: 'PRESTIGE x{n}',
    prestigeReq: '{n}',
    prestigeBtn: 'PRESTIGIO',
    prestigeReady: 'PRESTIGIO',
    prestigeConfirm: '¿PURGE & BOOT? El progreso se reiniciará. Multiplicador: x{n}',
    achTitle: 'LOGROS ({n}/12)',
    achFirstClick: 'Primer Click',
    achFirstClickDesc: 'Haz tu primer click',
    achClicker: 'Clickeador',
    achClickerDesc: 'Alcanza 1K clicks',
    achAddicted: 'Adicto',
    achAddictedDesc: 'Alcanza 10K clicks',
    achDataMiner: 'Minero de Datos',
    achDataMinerDesc: 'Gana 1M de datos totales',
    achDataLord: 'Señor de los Datos',
    achDataLordDesc: 'Gana 1B de datos totales',
    achHacker: 'Hacker',
    achHackerDesc: '5 mejoras a nivel 5+',
    achEliteHacker: 'Hacker Élite',
    achEliteHackerDesc: '10 mejoras a nivel 10+',
    achScavenger: 'Carroñero',
    achScavengerDesc: 'Compra 100 mejoras totales',
    achLucky: 'Suertudo',
    achLuckyDesc: 'Consigue 100 críticos',
    achAutoPilot: 'Piloto Automático',
    achAutoPilotDesc: 'Caballo de Troya nivel 5+',
    achCompletionist: 'Completista',
    achCompletionistDesc: 'Todas las mejoras nivel 1+',
    achPrestigeMaster: 'Maestro del Prestige',
    achPrestigeMasterDesc: '5 prestige',
    achSynergyMaster: 'Sinergias Maestras',
    achSynergyMasterDesc: 'Consigue todas las sinergias',
    achUnlocked: 'LOGRO DESBLOQUEADO: {name}',
    achUnlockedStatus: 'DESBLOQUEADO',
    achLockedStatus: 'BLOQUEADO',
    comboLabel: 'COMBO x{m} ({n})',
    skinTitle: 'SKINS',
    skinActive: 'ACTIVO',
    skinSelect: 'SELECCIONAR',
    skinDefault: 'Matrix Original',
    skinHacker: 'Neón Alto',
    skinNight: 'Modo Noche',
    skinFirewall: 'Alarma',
    skinNeon: 'Ciudad Neón',
    skinGolden: 'Oro',
    skinGlitch: 'Glitch',
    statsTitle: 'ESTADÍSTICAS',
    statTime: 'Tiempo jugado',
    statClicks: 'Clicks totales',
    statDataEarned: 'Datos totales',
    statClickPower: 'Poder de click',
    statDps: 'Datos por segundo',
    statCritChance: '% crítico',
    statCrits: 'Críticos totales',
    statUpgrades: 'Mejoras compradas',
    statPrestige: 'Prestige',
    statCombo: 'Combo actual',
    fwTitle: '⚠ FIREWALL DETECTED',
    fwIgnore: 'IGNORE',
    fwSuccess: 'ACCESO CONCEDIDO +{n}',
    fwFail: 'FIREWALL BLOQUEADO',
    upgrade: {
      terminal: { name: 'Terminal Básica', desc: 'Acceso shell inicial' },
      cpu: { name: 'CPU Rápida', desc: 'Procesador overclockeado' },
      scanner: { name: 'Escáner de Red', desc: 'Escanear puertos abiertos' },
      firewall: { name: 'Ruptura de Firewall', desc: 'Bypass de firewall' },
      ai: { name: 'Asistente IA', desc: 'IA de hackeo neuronal' },
      botnet: { name: 'Ejército Botnet', desc: 'Nodos zombie' },
      zeroday: { name: 'Día Cero', desc: 'Vulnerabilidad desconocida' },
      quantum: { name: 'Descifrado Cuántico', desc: 'Rompimiento de clave cuántica' },
      smith: { name: 'Agente Smith', desc: 'Corrompe la Matrix' },
      source: { name: 'La Fuente', desc: 'Acceso al programa primario' },
      critical: { name: 'Hack Crítico', desc: 'Probabilidad de daño x3' },
      sqlinjection: { name: 'Inyección SQL', desc: 'Reduce costos de mejoras' },
      trojan: { name: 'Caballo de Troya', desc: 'Auto-click cada 8s' },
      kernel: { name: 'Ataque al Kernel', desc: 'Multiplica poder de click' },
      zion: { name: 'Protocolo Zion', desc: 'Multiplica DPS' },
      rootkit: { name: 'Rootkit', desc: 'Gana DPS mientras offline' },
      evolution: { name: 'Evolución', desc: 'Adaptación genética al código' },
      transcend: { name: 'Trascender', desc: 'Ir más allá de la Matrix' },
      phantom: { name: 'Fantasma', desc: 'Ataque fantasmal indetectable' },
      overmind: { name: 'Supermente', desc: 'Inteligencia colectiva' },
      sniffer: { name: 'Analizador de Paquetes', desc: 'Intercepta paquetes' },
      bruteforce: { name: 'Fuerza Bruta', desc: 'Rompe contraseñas' },
      ddos: { name: 'Nodo DDoS', desc: 'Ataque distribuido' },
      ghost: { name: 'Protocolo Fantasma', desc: 'Intrusión invisible' },
      codered: { name: 'Código Rojo', desc: 'Propagación de gusano' },
      neural: { name: 'Interfaz Neural', desc: 'Enlace cerebral directo' },
      worm: { name: 'Gusano Morris', desc: 'Gusano auto-replicante' },
      sentinel: { name: 'Centinela', desc: 'Vigilancia de red global' },
      apocalypse: { name: 'Apocalipsis', desc: 'Protocolo de destrucción masiva' },
      collective: { name: 'Colectivo', desc: 'Red neuronal distribuida' },
      oracle: { name: 'Oráculo', desc: 'Predicción de vectores de ataque' },
      prime: { name: 'Programa Primario', desc: 'Código fuente de la Matrix' },
      cipher: { name: 'Cifrador', desc: 'Encriptación de nivel cuántico' },
      keymaker: { name: 'Creador de Llaves', desc: 'Acceso a todas las puertas' },

      // V2 — COMBO group
      rhythm: { name: 'Ritmo de Hackeo', desc: 'Clickea al ritmo de la Matrix' },
      flow: { name: 'Flujo Continuo', desc: 'Datos fluyendo sin interrupción' },
      momentum: { name: 'Impulso', desc: 'Aceleración bidireccional de datos' },
      adrenaline: { name: 'Adrenalina', desc: 'Reflejos sobrecargados' },

      // V2 — META group
      backdoor: { name: 'Puerta Trasera Persistente', desc: 'Puerta trasera siempre abierta' },
      wormhole: { name: 'Agujero de Gusano', desc: 'Distorsión del multiplicador crítico' },
      turbo: { name: 'Turbo', desc: 'Auto-click a velocidad extrema' },
      nexus: { name: 'Nexo de Datos', desc: 'Convergencia de click y DPS' },

      // V2 — CLICK group
      overdrive: { name: 'Sobrecarga', desc: 'Ataque de máxima potencia' },
      singularity: { name: 'Singularidad', desc: 'Colapso de datos en un punto' },
      omega: { name: 'Protocolo Omega', desc: 'Multiplicador de click definitivo' },

      // V2 — DPS group
      grid: { name: 'Malla Distribuida', desc: 'Procesamiento paralelo masivo' },
      infinite: { name: 'Bucle Infinito', desc: 'Cómputo sin fin' },
      genesis: { name: 'Protocolo Génesis', desc: 'Fundamento de la Matrix' },

      // V2 — SPECIAL expansion
      cortex: { name: 'Corteza Neural', desc: 'Capa de procesamiento neuronal' },
      leech: { name: 'Drenaje de Datos', desc: 'Succiona datos automáticamente' },
      parasite: { name: 'Parásito', desc: 'Acelera el auto-click' },
      proxy: { name: 'Proxy Anónimo', desc: 'Conexiones encriptadas' },
    },
    shopAutoBuy: 'Compra automática de la mejora más barata',
    prestigePreviewTitle: '⚠ PURGE & BOOT',
    prestigePreviewMult: 'MULTIPLICADOR',
    prestigePreviewCurrent: 'ACTUAL',
    prestigePreviewNext: 'SIGUIENTE',
    prestigePreviewRewards: 'RECOMPENSAS',
    prestigePreviewPoints: 'PUNTOS PRESTIGE',
    prestigePreviewStart: 'DATOS INICIALES',
    prestigePreviewReset: 'SE REINICIA',
    prestigePreviewData: 'Datos actuales',
    prestigePreviewUpgrades: 'Mejoras',
    prestigePreviewKept: 'SE CONSERVA',
    prestigePreviewAch: 'Logros',
    prestigePreviewSkins: 'Skins',
    prestigePreviewShop: 'Mejoras de tienda',
    prestigePreviewCancel: 'CANCELAR',
    prestigePreviewConfirm: 'PURGAR',
    shopClickBoost: '+25% Poder de click por nivel',
    shopDpsBoost: '+25% DPS por nivel',
    shopStartData: '1K datos iniciales por nivel',
    shopComboBoost: '+0.05 multiplicador de combo por nivel',
    shopCritBoost: '+5% probabilidad crítica por nivel',
    eventLeak: '⚠ FUGA: -5% datos, +50% DPS {dur}s — ¡HAKEA para recuperar!',
    eventCrash: '📉 CRYPTO CRASH: -20% costo {dur}s',
    eventOverclock: '⚡ OVERCLOCK: Click x3 durante {dur}s',
    eventWindfall: '💰 GANANCIA INESPERADA: +10% datos',
    eventDdos: '🔥 DDoS: +100% DPS durante {dur}s',
    bossTitle: '⚠ INTRUSIÓN DE BOSS',
    bossInfo: 'GENERA {n} EN {t}s',
    bossFail: 'INTRUSIÓN FALLIDA',
    bossSuccess: '¡INTRUSIÓN EXITOSA! +{n}',
    prestigeShopTitle: 'TIENDA DE PRESTIGE',
    prestigePoints: 'PUNTOS: {n}',
    shopLevel: 'NVL {n}/{m}',
    shopCost: '{n} PP',
    shopBtnBuy: 'COMPRAR',
    shopBtnMax: 'MÁX',
    autoBuyOn: 'AUTO: ON',
    autoBuyOff: 'AUTO: OFF',
    exportOk: 'SAVE COPIADO AL PORTAPAPELES',
    exportFail: 'ERROR AL EXPORTAR',
    importOk: 'SAVE IMPORTADO',
    importFail: 'SAVE INVÁLIDO',
    settingsBtn: 'OPCIONES',
    settingsTitle: '> OPCIONES_',
    settingsLang: 'IDIOMA',
    settingsAudio: 'SONIDO',
    settingsData: 'DATOS',
    settingsReset: 'REINICIAR',
    settingsResetDesc: 'Borra todo el progreso, logros, skins, prestige y empieza de cero.',
    settingsResetBtn: '☠ BORRAR TODOS LOS DATOS',
    settingsResetConfirmMsg: '¿Estás seguro? Esto no se puede deshacer.',
    resetCancel: 'CANCELAR',
    resetExecute: '☠ ELIMINAR TODO',
    resetDone: 'TODO EL PROGRESO HA SIDO ELIMINADO',
    offlineTitle: '▸ RESUMEN OFFLINE_',
    offlineTime: 'TIEMPO: {n}',
    offlineData: 'DATOS: +{n}',
    offlineDesc: 'M I E N T R A S   E S T A B A S   F U E R A ...',
    offlineClose: 'CERRAR',
    tutorialTitle: '> TUTORIAL_',
    tutorialStep0: 'Haz clic en ./hack.exe para generar datos',
    tutorialStep1: 'Compra mejoras en el panel derecho haciendo clic en ellas',
    tutorialStep2: 'Sigue comprando mejoras para aumentar tu poder',
    tutorialStep3: 'Haz clics rápidos para activar la racha COMBO y multiplicar ganancias',
    tutorialStep4: 'Llega a PRESTIGE para reiniciar y multiplicar tu poder permanentemente',
    tutorialDone: '✓ LISTO',
    tutorialSkip: 'SALTAR TUTORIAL',
    typingTitle: '⚠ HACKEO POR TECLADO',
    typingIgnore: 'IGNORAR',
    typingSuccess: '✔ ACCESO CONCEDIDO +{n}',
    typingFail: '✘ ACCESO DENEGADO',
    typingPenalty: '✘ FALLO CRÍTICO -{n}',
    typingInput: '>_',
    sqlInjectTarget: 'Inyectar SQL en: 0x{target}',
    sqlInjectWord: 'Escribe: "{word}"',
    bruteForceKey: 'Clave: {key}',
    bruteForceHint: 'Reescribe la clave exactamente',
    decodePrompt: 'Decodifica el binario:',
    decodeHint: 'Escribe el texto descifrado',
    commandChainPrompt: 'Comandos restantes: {n}',
    commandChainHint: 'Escribe "{cmd}" y presiona Enter',
    captchaPrompt: 'Captcha:',
    captchaHint: 'Escribe lo que ves',
    bossShield: 'ESCUDO: {n} clics',
    bossShieldHint: '¡Hackea para romper el escudo!',
    bossRegen: 'REGENERACIÓN ACTIVA',
    bossRegenHint: '¡Mantén el ataque constante!',
    bossCounter: 'CONTRATAQUE',
    bossCounterHint: '¡Completa rápido o perderás datos!',
  },
  en: {
    title: 'MATRIX HACK TERMINAL v1.0',
    headerPrompt: 'root@matrix:~$',
    handle: '>> NEO_001',
    level: 'LEVEL: {n}',
    mb: 'MB',
    btnPrompt: '[root@matrix]~$',
    btnText: './hack.exe',
    secure: '[CONNECTION SECURE]',
    autoSave: 'AUTO-SAVE ACTIVE',
    saved: 'SAVED {time}',
    offline: 'OFFLINE +{n}',
    synergyDivider: ' | ',
    synergyScanner: 'SCANNER→CPU +{n} DPS',
    synergyArch: 'ARCHITECT x{n}',
    critText: 'CRIT! x3',
    autoPrefix: '[AUTO]',
    panelTitle: '> UPGRADES_',
    buyModeLabel: 'BUY:',
    buyMax: 'MAX',
    autoBuyOn: 'AUTO: ON',
    autoBuyOff: 'AUTO: OFF',
    achBtn: 'ACHIEVEMENTS',
    statsBtn: 'STATS',
    skinBtn: 'SKINS',
    prestigeShopBtn: '◆ SHOP',
    exportBtn: '↑ EXPORT',
    importBtn: '↓ IMPORT',
    groupClick: '> CLICK_',
    groupDps: '> DPS_',
    groupSpecial: '> SPECIAL_',
    groupMult: '> MULTIPLIERS_',
    milestoneLabel: '{n}',
    upgradeCount: '{n}/{m}',
    cardLvl: 'LVL',
    effectClick: 'CLICK +{n}',
    effectDps: 'DPS +{n}',
    effectCrit: '{n}% CRIT',
    effectDiscount: '-{n}% COST',
    effectAutoclick: '{n} click/8s',
    effectMultClick: 'CLICK x{n}',
    effectMultDps: 'DPS x{n}',
    effectOffline: '{n}% OFFLINE',
    effectClickDps: 'CLICK/DPS +{n}',
    effectCritDmg: 'CRIT x{n}',
    effectAutoSpeed: '-{n}ms AUTO',
    effectComboBoost: '+{n} COMBO',
    synergyBtn: 'SYNERGIES',
    synergyTitle: '> SYNERGIES_',
    synergyScannerName: 'Scanner→CPU',
    synergyArchName: 'Architect',
    synergyReqs: 'Requirements:',
    synergyEffect: 'Effect:',
    synergyUnlocked: '✓ UNLOCKED',
    synergyUnknown: '??',
    synergyScannerReqs: ['Scanner LVL 5+', 'CPU LVL 1+'],
    synergyScannerEffect: 'DPS +{n}',
    synergyArchLabel: '1 upgrade at LVL 10+',
    synergyArchEffect: 'DPS x{n}',
    synergyOverdriveName: 'Volt Rush',
    synergyOverdriveEffect: 'CLICK x1.5',
    synergyCipherName: 'Master Key',
    synergyCipherEffect: 'DPS x2',
    synergyComboName: 'Flow State',
    synergyComboEffect: 'COMBO MAX +10',
    synergyMetaName: 'Stack Overflow',
    synergyMetaEffect: '-5% COST',
    groupCombo: '> COMBO_',
    groupMeta: '> META_',
    statClick: 'CLICK',
    statDps: 'DPS',
    statCrit: 'CRIT',
    statDiscount: 'DISCOUNT',
    unitPercent: '%',
    offlineExtra: ' EARNED',
    resetConfirm: 'Reset all game data?',
    prestigeLabel: 'PRESTIGE x{n}',
    prestigeReq: '{n}',
    prestigeBtn: 'PRESTIGE',
    prestigeReady: 'PRESTIGE',
    prestigeConfirm: 'PURGE & BOOT? Progress will reset. Multiplier: x{n}',
    achTitle: 'ACHIEVEMENTS ({n}/12)',
    achFirstClick: 'First Click',
    achFirstClickDesc: 'Make your first click',
    achClicker: 'Clicker',
    achClickerDesc: 'Reach 1K clicks',
    achAddicted: 'Addicted',
    achAddictedDesc: 'Reach 10K clicks',
    achDataMiner: 'Data Miner',
    achDataMinerDesc: 'Earn 1M total data',
    achDataLord: 'Data Lord',
    achDataLordDesc: 'Earn 1B total data',
    achHacker: 'Hacker',
    achHackerDesc: '5 upgrades at level 5+',
    achEliteHacker: 'Elite Hacker',
    achEliteHackerDesc: '10 upgrades at level 10+',
    achScavenger: 'Scavenger',
    achScavengerDesc: 'Buy 100 total upgrades',
    achLucky: 'Lucky',
    achLuckyDesc: 'Land 100 crits',
    achAutoPilot: 'Auto Pilot',
    achAutoPilotDesc: 'Trojan Horse level 5+',
    achCompletionist: 'Completionist',
    achCompletionistDesc: 'All upgrades level 1+',
    achPrestigeMaster: 'Prestige Master',
    achPrestigeMasterDesc: '5 prestiges',
    achSynergyMaster: 'Synergy Master',
    achSynergyMasterDesc: 'Unlock all synergies',
    achUnlocked: 'ACHIEVEMENT UNLOCKED: {name}',
    achUnlockedStatus: 'UNLOCKED',
    achLockedStatus: 'LOCKED',
    comboLabel: 'COMBO x{m} ({n})',
    skinTitle: 'SKINS',
    skinActive: 'ACTIVE',
    skinSelect: 'SELECT',
    skinDefault: 'Matrix Original',
    skinHacker: 'High Neon',
    skinNight: 'Night Mode',
    skinFirewall: 'Firewall',
    skinNeon: 'Neon City',
    skinGolden: 'Golden',
    skinGlitch: 'Glitch Core',
    statsTitle: 'STATISTICS',
    statTime: 'Play time',
    statClicks: 'Total clicks',
    statDataEarned: 'Data earned',
    statClickPower: 'Click power',
    statDps: 'Data per second',
    statCritChance: 'Crit chance',
    statCrits: 'Total crits',
    statUpgrades: 'Upgrades bought',
    statPrestige: 'Prestige',
    statCombo: 'Current combo',
    fwTitle: '⚠ FIREWALL DETECTED',
    fwIgnore: 'IGNORE',
    fwSuccess: 'ACCESS GRANTED +{n}',
    fwFail: 'FIREWALL BLOCKED',
    upgrade: {
      terminal: { name: 'Basic Terminal', desc: 'Init shell access' },
      cpu: { name: 'Faster CPU', desc: 'Overclock processor' },
      scanner: { name: 'Network Scanner', desc: 'Scan open ports' },
      firewall: { name: 'Firewall Crack', desc: 'Bypass firewall' },
      ai: { name: 'AI Assistant', desc: 'Neural hack AI' },
      botnet: { name: 'Botnet Army', desc: 'Zombie nodes' },
      zeroday: { name: 'Zero-Day Exploit', desc: 'Unknown vulnerability' },
      quantum: { name: 'Quantum Decrypt', desc: 'Quantum key crack' },
      smith: { name: 'Agent Smith', desc: 'Corrupt the Matrix' },
      source: { name: 'The Source', desc: 'Access the prime program' },
      critical: { name: 'Critical Hack', desc: 'Chance for 3x damage' },
      sqlinjection: { name: 'SQL Injection', desc: 'Reduce upgrade costs' },
      trojan: { name: 'Trojan Horse', desc: 'Auto-click every 8s' },
      kernel: { name: 'Kernel Exploit', desc: 'Multiplies click power' },
      zion: { name: 'Zion Protocol', desc: 'Multiplies DPS' },
      rootkit: { name: 'Rootkit', desc: 'Earn DPS while offline' },
      evolution: { name: 'Evolution', desc: 'Genetic code adaptation' },
      transcend: { name: 'Transcend', desc: 'Go beyond the Matrix' },
      phantom: { name: 'Phantom', desc: 'Undetectable ghost attack' },
      overmind: { name: 'Overmind', desc: 'Collective intelligence' },
      sniffer: { name: 'Packet Sniffer', desc: 'Intercept data packets' },
      bruteforce: { name: 'Brute Force', desc: 'Crack passwords' },
      ddos: { name: 'DDoS Node', desc: 'Distributed attack' },
      ghost: { name: 'Ghost Protocol', desc: 'Invisible intrusion' },
      codered: { name: 'Code Red', desc: 'Worm propagation' },
      neural: { name: 'Neural Interface', desc: 'Direct brain link' },
      worm: { name: 'Morris Worm', desc: 'Self-replicating worm' },
      sentinel: { name: 'Sentinel', desc: 'Global network surveillance' },
      apocalypse: { name: 'Apocalypse', desc: 'Mass destruction protocol' },
      collective: { name: 'Collective', desc: 'Distributed neural network' },
      oracle: { name: 'Oracle', desc: 'Attack vector prediction' },
      prime: { name: 'Prime Program', desc: 'Source code of the Matrix' },
      cipher: { name: 'Cipher', desc: 'Quantum-level encryption' },
      keymaker: { name: 'Keymaker', desc: 'Access to all doors' },

      // V2 — COMBO group
      rhythm: { name: 'Hack Rhythm', desc: 'Click to the rhythm of the Matrix' },
      flow: { name: 'Continuous Flow', desc: 'Uninterrupted data stream' },
      momentum: { name: 'Momentum', desc: 'Bidirectional data boost' },
      adrenaline: { name: 'Adrenaline Rush', desc: 'Overclocked reflexes' },

      // V2 — META group
      backdoor: { name: 'Persistent Backdoor', desc: 'Always open backdoor' },
      wormhole: { name: 'Wormhole', desc: 'Critical multiplier distortion' },
      turbo: { name: 'Turbo', desc: 'Extreme auto-click speed' },
      nexus: { name: 'Data Nexus', desc: 'Click and DPS convergence' },

      // V2 — CLICK group
      overdrive: { name: 'Overdrive', desc: 'Maximum power attack' },
      singularity: { name: 'Singularity', desc: 'Data collapse into a point' },
      omega: { name: 'Omega Protocol', desc: 'Ultimate click multiplier' },

      // V2 — DPS group
      grid: { name: 'Distributed Grid', desc: 'Massive parallel processing' },
      infinite: { name: 'Infinite Loop', desc: 'Endless computation' },
      genesis: { name: 'Genesis Protocol', desc: 'Foundation of the Matrix' },

      // V2 — SPECIAL expansion
      cortex: { name: 'Neural Cortex', desc: 'Neural processing layer' },
      leech: { name: 'Data Leech', desc: 'Siphons data automatically' },
      parasite: { name: 'Parasite', desc: 'Accelerates auto-click' },
      proxy: { name: 'Anonymous Proxy', desc: 'Encrypted connections' },
    },
    shopAutoBuy: 'Auto-buy the cheapest upgrade',
    prestigePreviewTitle: '⚠ PURGE & BOOT',
    prestigePreviewMult: 'MULTIPLIER',
    prestigePreviewCurrent: 'CURRENT',
    prestigePreviewNext: 'NEXT',
    prestigePreviewRewards: 'REWARDS',
    prestigePreviewPoints: 'PRESTIGE POINTS',
    prestigePreviewStart: 'STARTING DATA',
    prestigePreviewReset: 'RESETS',
    prestigePreviewData: 'Current data',
    prestigePreviewUpgrades: 'Upgrades',
    prestigePreviewKept: 'PRESERVED',
    prestigePreviewAch: 'Achievements',
    prestigePreviewSkins: 'Skins',
    prestigePreviewShop: 'Shop upgrades',
    prestigePreviewCancel: 'CANCEL',
    prestigePreviewConfirm: 'PURGE',
    shopClickBoost: '+25% Click power per level',
    shopDpsBoost: '+25% DPS per level',
    shopStartData: '1K starting data per level',
    shopComboBoost: '+0.05 combo multiplier per level',
    shopCritBoost: '+5% crit chance per level',
    eventLeak: '⚠ LEAK: -5% data, +50% DPS {dur}s — HACK to recover!',
    eventCrash: '📉 CRYPTO CRASH: -20% cost {dur}s',
    eventOverclock: '⚡ OVERCLOCK: Click x3 for {dur}s',
    eventWindfall: '💰 WINDFALL: +10% data',
    eventDdos: '🔥 DDoS: +100% DPS for {dur}s',
    bossTitle: '⚠ BOSS INTRUSION',
    bossInfo: 'GENERATE {n} IN {t}s',
    bossFail: 'INTRUSION FAILED',
    bossSuccess: 'INTRUSION SUCCESS! +{n}',
    prestigeShopTitle: 'PRESTIGE SHOP',
    prestigePoints: 'POINTS: {n}',
    shopLevel: 'LVL {n}/{m}',
    shopCost: '{n} PP',
    shopBtnBuy: 'BUY',
    shopBtnMax: 'MAX',
    autoBuyOn: 'AUTO: ON',
    autoBuyOff: 'AUTO: OFF',
    exportOk: 'SAVE COPIED TO CLIPBOARD',
    exportFail: 'EXPORT ERROR',
    importOk: 'SAVE IMPORTED',
    importFail: 'INVALID SAVE',
    settingsBtn: 'OPTIONS',
    settingsTitle: '> OPTIONS_',
    settingsLang: 'LANGUAGE',
    settingsAudio: 'AUDIO',
    settingsData: 'DATA',
    settingsReset: 'RESET',
    settingsResetDesc: 'Wipe all progress, achievements, skins, prestige &amp; start from zero.',
    settingsResetBtn: '☠ DELETE ALL DATA',
    settingsResetConfirmMsg: 'Are you sure? This cannot be undone.',
    resetCancel: 'CANCEL',
    resetExecute: '☠ ERASE EVERYTHING',
    resetDone: 'ALL PROGRESS HAS BEEN WIPED',
    offlineTitle: '▸ OFFLINE SUMMARY_',
    offlineTime: 'TIME: {n}',
    offlineData: 'DATA: +{n}',
    offlineDesc: 'W H I L E   Y O U   W E R E   A W A Y ...',
    offlineClose: 'CLOSE',
    tutorialTitle: '> TUTORIAL_',
    tutorialStep0: 'Click ./hack.exe to generate data',
    tutorialStep1: 'Buy upgrades in the right panel by clicking them',
    tutorialStep2: 'Keep buying upgrades to increase your power',
    tutorialStep3: 'Click rapidly to activate COMBO streaks and multiply earnings',
    tutorialStep4: 'Reach PRESTIGE to reset and permanently multiply your power',
    tutorialDone: '✓ DONE',
    tutorialSkip: 'SKIP TUTORIAL',
    typingTitle: '⚠ TYPING HACK',
    typingIgnore: 'IGNORE',
    typingSuccess: '✔ ACCESS GRANTED +{n}',
    typingFail: '✘ ACCESS DENIED',
    typingPenalty: '✘ CRITICAL FAIL -{n}',
    typingInput: '>_',
    sqlInjectTarget: 'SQL Inject into: 0x{target}',
    sqlInjectWord: 'Type: "{word}"',
    bruteForceKey: 'Key: {key}',
    bruteForceHint: 'Rewrite the key exactly',
    decodePrompt: 'Decode the binary:',
    decodeHint: 'Type the decoded text',
    commandChainPrompt: 'Commands remaining: {n}',
    commandChainHint: 'Type "{cmd}" and press Enter',
    captchaPrompt: 'Captcha:',
    captchaHint: 'Type what you see',
    bossShield: 'SHIELD: {n} clicks',
    bossShieldHint: 'Hack to break the shield!',
    bossRegen: 'REGENERATION ACTIVE',
    bossRegenHint: 'Keep the attack constant!',
    bossCounter: 'COUNTERATTACK',
    bossCounterHint: 'Finish fast or lose data!',
  },
};

function t(key, replacements) {
  const lang = state && state.lang ? state.lang : 'es';
  const parts = key.split('.');
  let val = STRINGS[lang];
  for (const p of parts) {
    if (val == null) return '?' + key;
    val = val[p];
  }
  if (val == null) return '?' + key;
  if (replacements) {
    for (const [k, v] of Object.entries(replacements)) {
      val = val.replace('{' + k + '}', v);
    }
  }
  return val;
}

/* --- CONFIG --- */
const CONFIG = {
  // Cost
  COST_EXP_UNLIMITED: 1.15,
  COST_EXP_LIMITED: 1.25,
  COST_DISCOUNT_MIN: 0.1,
  // Combo
  COMBO_TIMEOUT_MS: 1000,
  COMBO_MAX: 50,
  COMBO_MULT_PER_STACK: 0.1,
  COMBO_BREAK_ANIM_MS: 300,
  // Auto
  AUTO_INTERVAL_DEFAULT: 8000,
  AUTO_INTERVAL_MIN: 2000,
  AUTO_INTERVAL_MAX: 8000,
  AUTO_BUY_INTERVAL_MS: 500,
  // Crit
  CRIT_MULTIPLIER_BASE: 3,
  // Combo boost cap
  MAX_COMBO_MULT: 5,
  COMBO_BOOST_LIMIT: 50,
  // Architect
  ARCHITECT_BONUS: 0.05,
  // Prestige
  PRESTIGE_MULT_FACTOR: 1.5,
  PRESTIGE_BASE_REQ: 500000,
  PRESTIGE_GLITCH_DELAY_MS: 1600,
  // Boss
  BOSS_TIME_BASE: 15,
  BOSS_TIME_MIN: 5,
  BOSS_TIME_DIVISOR: 5,
  BOSS_LEVEL_SCALE: 0.15,
  BOSS_REWARD_FRACTION: 0.5,
  BOSS_SCHEDULE_BASE_MS: 120000,
  BOSS_SCHEDULE_RANDOM_MS: 60000,
  BOSS_DISPLAY_DELAY_MS: 2000,
  // Firewall
  FW_NODE_BASE: 3,
  FW_NODE_DIVISOR: 5,
  FW_NODE_MAX: 8,
  FW_TIME_BASE: 5,
  FW_TIME_DIVISOR: 10,
  FW_TIME_MIN: 2,
  FW_REWARD_DPS_MULT: 10,
  FW_REWARD_LEVEL_SCALE: 0.1,
  FW_SCHEDULE_BASE_MS: 60000,
  FW_SCHEDULE_RANDOM_MS: 60000,
  FW_DISPLAY_DELAY_MS: 2000,
  // Events
  EVENT_SCHEDULE_BASE_MS: 45000,
  EVENT_SCHEDULE_RANDOM_MS: 45000,
  EVENT_WINDFALL_PERCENT: 0.1,
  EVENT_LEAK_PENALTY: 0.05,
  EVENT_WINDFALL_DISPLAY_MS: 3000,
  // Offline
  OFFLINE_ROOTKIT_MULT: 0.15,
  // Animations
  CRIT_ANIM_DURATION_MS: 150,
  BUY_FLASH_DURATION_MS: 400,
  SAVE_STATUS_DURATION_MS: 2000,
  // Game loop
  GAME_LOOP_TICK_MS: 100,
  TERM_NOISE_INTERVAL_MS: 3000,
  // Prestige shop
  SHOP_CLICK_BOOST: 0.25,
  SHOP_DPS_BOOST: 0.25,
  SHOP_START_DATA: 1000,
  SHOP_COMBO_BOOST: 0.05,
  SHOP_CRIT_BOOST: 5,
  // Event stat multipliers
  EVENT_OVERCLOCK_CLICK: 3,
  EVENT_DDOS_DPS: 2,
  EVENT_CRYPTO_CRASH_COST: 0.8,
  EVENT_DATA_LEAK_DPS: 1.5,
  // Buy mode
  BUY_MAX_THRESHOLD: 999,
  // Boss scheduling min DPS
  BOSS_SCHEDULE_MIN_DPS: 1,
  BOSS_SCHEDULE_RETRY_MS: 10000,
};

const RARITIES = ['common', 'uncommon', 'rare', 'epic', 'legendary'];

const UPGRADE_DEFS = [
  { id: 'terminal', cost: 10, effect: 'click', value: 1, icon: '>', unlockAt: 0, rarity: 'common' },
  { id: 'cpu', cost: 25, effect: 'dps', value: 0.5, icon: '[]', unlockAt: 0, rarity: 'common' },
  { id: 'scanner', cost: 50, effect: 'click', value: 2, icon: '@', unlockAt: 0, rarity: 'common' },
  { id: 'firewall', cost: 100, effect: 'dps', value: 2, icon: '#', unlockAt: 0, rarity: 'common' },
  { id: 'ai', cost: 250, effect: 'click', value: 5, icon: '&', unlockAt: 0, rarity: 'common' },
  { id: 'botnet', cost: 500, effect: 'dps', value: 5, icon: '*', unlockAt: 0, rarity: 'common' },
  { id: 'zeroday', cost: 1000, effect: 'click', value: 15, icon: '!', unlockAt: 500, rarity: 'uncommon' },
  { id: 'quantum', cost: 2500, effect: 'dps', value: 15, icon: '?', unlockAt: 1000, rarity: 'uncommon' },
  { id: 'smith', cost: 5000, effect: 'click', value: 50, icon: '$', unlockAt: 2500, rarity: 'uncommon' },
  { id: 'source', cost: 10000, effect: 'dps', value: 50, icon: '%', unlockAt: 5000, rarity: 'uncommon' },
  { id: 'critical', cost: 15000, effect: 'crit', value: 4, icon: '!', unlockAt: 10000, rarity: 'uncommon' },
  { id: 'sqlinjection', cost: 25000, effect: 'discount', value: 2, icon: '$', unlockAt: 10000, rarity: 'uncommon' },
  { id: 'trojan', cost: 40000, effect: 'autoclick', value: 1, icon: '@', unlockAt: 20000, rarity: 'uncommon' },
  { id: 'sniffer', cost: 100000, effect: 'dps', value: 75, icon: '~', unlockAt: 75000, rarity: 'uncommon' },
  { id: 'bruteforce', cost: 250000, effect: 'click', value: 150, icon: '!', unlockAt: 150000, rarity: 'uncommon' },
  { id: 'ddos', cost: 750000, effect: 'dps', value: 500, icon: '*', unlockAt: 400000, rarity: 'uncommon' },
  { id: 'ghost', cost: 2000000, effect: 'click', value: 400, icon: '?', unlockAt: 1000000, rarity: 'uncommon' },
  { id: 'kernel', cost: 80000, effect: 'mult_click', value: 1.15, icon: '*', unlockAt: 40000, rarity: 'rare' },
  { id: 'zion', cost: 150000, effect: 'mult_dps', value: 1.15, icon: '#', unlockAt: 75000, rarity: 'rare' },
  { id: 'rootkit', cost: 300000, effect: 'offline', value: 15, icon: '&', unlockAt: 150000, rarity: 'rare' },
  { id: 'evolution', cost: 5000000, effect: 'mult_click', value: 1.2, icon: '+', unlockAt: 3000000, rarity: 'rare' },
  { id: 'transcend', cost: 10000000, effect: 'mult_dps', value: 1.2, icon: '=', unlockAt: 5000000, rarity: 'rare' },
  { id: 'codered', cost: 10000000, effect: 'click', value: 5000, icon: '#', unlockAt: 5000000, rarity: 'rare' },
  { id: 'neural', cost: 25000000, effect: 'dps', value: 10000, icon: '@', unlockAt: 12000000, rarity: 'rare' },
  { id: 'phantom', cost: 50000000, effect: 'click', value: 1000, icon: '~', unlockAt: 25000000, rarity: 'rare' },
  { id: 'overmind', cost: 100000000, effect: 'dps', value: 500, icon: '@', unlockAt: 25000000, rarity: 'rare' },
  { id: 'rhythm', cost: 5000, effect: 'click', value: 20, icon: '♫', unlockAt: 2500, maxLevel: 10, rarity: 'rare' },
  { id: 'flow', cost: 20000, effect: 'dps', value: 20, icon: '≈', unlockAt: 10000, maxLevel: 10, rarity: 'rare' },
  { id: 'momentum', cost: 100000, effect: 'clickDps', value: 10, icon: '↯', unlockAt: 50000, maxLevel: 10, rarity: 'rare' },
  { id: 'adrenaline', cost: 500000, effect: 'comboBoost', value: 0.02, icon: '⚡', unlockAt: 250000, maxLevel: 10, rarity: 'rare' },
  { id: 'backdoor', cost: 50000, effect: 'discount', value: 1, icon: '◄', unlockAt: 20000, maxLevel: 5, rarity: 'rare' },
  { id: 'wormhole', cost: 2000000, effect: 'critDmg', value: 0.5, icon: '◎', unlockAt: 1000000, maxLevel: 5, rarity: 'rare' },
  { id: 'worm', cost: 500000000, effect: 'click', value: 500000, icon: '~', unlockAt: 200000000, rarity: 'epic' },
  { id: 'sentinel', cost: 5000000000, effect: 'dps', value: 500000, icon: '%', unlockAt: 2000000000, rarity: 'epic' },
  { id: 'oracle', cost: 50000000000, effect: 'mult_click', value: 1.5, icon: '?', unlockAt: 20000000000, rarity: 'epic' },
  { id: 'apocalypse', cost: 100000000000, effect: 'click', value: 100000, icon: '!', unlockAt: 50000000000, rarity: 'epic' },
  { id: 'collective', cost: 500000000000, effect: 'dps', value: 50000, icon: '#', unlockAt: 200000000000, rarity: 'epic' },
  { id: 'prime', cost: 1000000000000, effect: 'mult_dps', value: 1.5, icon: '$', unlockAt: 500000000000, rarity: 'epic' },
  { id: 'cortex', cost: 5000000, effect: 'critDmg', value: 0.3, icon: '◈', unlockAt: 2500000, maxLevel: 5, rarity: 'epic' },
  { id: 'leech', cost: 50000000, effect: 'autoclick', value: 1, icon: '¤', unlockAt: 25000000, rarity: 'epic' },
  { id: 'parasite', cost: 500000000, effect: 'autoSpeed', value: 300, icon: '◀', unlockAt: 200000000, maxLevel: 5, rarity: 'epic' },
  { id: 'proxy', cost: 5000000000, effect: 'discount', value: 2, icon: '▣', unlockAt: 2000000000, maxLevel: 5, rarity: 'epic' },
  { id: 'turbo', cost: 10000000, effect: 'autoSpeed', value: 500, icon: '»', unlockAt: 5000000, maxLevel: 5, rarity: 'epic' },
  { id: 'nexus', cost: 100000000, effect: 'clickDps', value: 2000, icon: '◆', unlockAt: 50000000, maxLevel: 5, rarity: 'epic' },
  { id: 'overdrive', cost: 50000000000, effect: 'click', value: 50000, icon: '!', unlockAt: 20000000000, rarity: 'epic' },
  { id: 'grid', cost: 50000000000, effect: 'dps', value: 25000, icon: '#', unlockAt: 20000000000, rarity: 'epic' },
  { id: 'cipher', cost: 10000000000000, effect: 'mult_click', value: 2, icon: '?', unlockAt: 5000000000000, rarity: 'legendary', maxLevel: 5, legendaryReq: { achievements: ['elite_hacker'], minPrestige: 1 } },
  { id: 'keymaker', cost: 100000000000000, effect: 'mult_dps', value: 2, icon: '$', unlockAt: 50000000000000, rarity: 'legendary', maxLevel: 5, legendaryReq: { achievements: ['completionist'], minPrestige: 3 } },
  { id: 'singularity', cost: 50000000000000, effect: 'click', value: 10000000, icon: '@', unlockAt: 20000000000000, rarity: 'legendary', maxLevel: 10, legendaryReq: { upgrades: ['oracle'] } },
  { id: 'infinite', cost: 50000000000000, effect: 'dps', value: 5000000, icon: '%', unlockAt: 20000000000000, rarity: 'legendary', maxLevel: 10, legendaryReq: { upgrades: ['prime'] } },
  { id: 'omega', cost: 1000000000000000, effect: 'mult_click', value: 3, icon: '?', unlockAt: 500000000000000, rarity: 'legendary', maxLevel: 3, legendaryReq: { upgrades: ['cipher', 'singularity'] } },
  { id: 'genesis', cost: 1000000000000000, effect: 'mult_dps', value: 3, icon: '$', unlockAt: 500000000000000, rarity: 'legendary', maxLevel: 3, legendaryReq: { upgrades: ['keymaker', 'infinite'] } },
];

const UPGRADE_GROUPS = [
  { id: 'click', labelKey: 'groupClick', ids: ['terminal', 'scanner', 'ai', 'zeroday', 'smith', 'bruteforce', 'ghost', 'phantom', 'codered', 'worm', 'apocalypse', 'overdrive', 'singularity', 'omega'] },
  { id: 'dps', labelKey: 'groupDps', ids: ['cpu', 'firewall', 'botnet', 'quantum', 'source', 'sniffer', 'overmind', 'ddos', 'neural', 'sentinel', 'collective', 'grid', 'infinite', 'genesis'] },
  { id: 'special', labelKey: 'groupSpecial', ids: ['critical', 'sqlinjection', 'trojan', 'cortex', 'leech', 'parasite', 'proxy'] },
  { id: 'mult', labelKey: 'groupMult', ids: ['kernel', 'zion', 'rootkit', 'evolution', 'transcend', 'oracle', 'prime', 'cipher', 'keymaker'] },
  { id: 'combo', labelKey: 'groupCombo', ids: ['rhythm', 'flow', 'momentum', 'adrenaline'] },
  { id: 'meta', labelKey: 'groupMeta', ids: ['backdoor', 'wormhole', 'turbo', 'nexus'] },
];

const MILESTONES = [100, 1000, 10000, 100000, 1000000, 10000000, 100000000, 1000000000, 100000000000, 10000000000000];

const LEVEL_THRESHOLDS = [0, 100, 500, 2000, 5000, 15000, 50000, 150000, 500000, 1500000, 5000000, 50000000, 500000000];

const ACHIEVEMENT_DEFS = [
  { id: 'first_click', bonus: { clickPercent: 10 } },
  { id: 'clicker', bonus: { clickPercent: 20 } },
  { id: 'addicted', bonus: { clickPercent: 50 } },
  { id: 'data_miner', bonus: { dpsPercent: 10 } },
  { id: 'data_lord', bonus: { dpsPercent: 50 } },
  { id: 'hacker', bonus: { dpsPercent: 15 } },
  { id: 'elite_hacker', bonus: { dpsPercent: 30 } },
  { id: 'scavenger', bonus: { discountFlat: 5 } },
  { id: 'lucky', bonus: { critPercent: 5 } },
  { id: 'auto_pilot', bonus: { autoclickExtra: 1 } },
  { id: 'completionist', bonus: { dpsPercent: 100 } },
  { id: 'prestige_master', bonus: { prestigeExtra: 0.5 } },
  { id: 'synergy_master', bonus: { dpsPercent: 50 } },
];

const VISUAL_SKINS = [
  { id: 'default', nameKey: 'skinDefault', cost: 0, colors: { head: '200, 255, 200', body: '0, 255, 0', alpha: 0.3, shadow: '#00ff00', scanline: 'rgba(0, 255, 0, 0.03)' }, speedMult: 1 },
  { id: 'hacker', nameKey: 'skinHacker', cost: 50000, colors: { head: '100, 255, 100', body: '0, 200, 0', alpha: 0.4, shadow: '#00ff00', scanline: 'rgba(0, 255, 0, 0.05)' }, speedMult: 1.2 },
  { id: 'night', nameKey: 'skinNight', cost: 100000, colors: { head: '100, 200, 255', body: '0, 150, 255', alpha: 0.35, shadow: '#0099ff', scanline: 'rgba(0, 150, 255, 0.04)' }, speedMult: 1 },
  { id: 'firewall', nameKey: 'skinFirewall', cost: 250000, colors: { head: '255, 150, 100', body: '255, 80, 0', alpha: 0.35, shadow: '#ff4400', scanline: 'rgba(255, 68, 0, 0.04)' }, speedMult: 1.5 },
  { id: 'neon', nameKey: 'skinNeon', cost: 500000, colors: { head: '255, 100, 255', body: '200, 0, 255', alpha: 0.35, shadow: '#cc00ff', scanline: 'rgba(200, 0, 255, 0.04)' }, speedMult: 1 },
  { id: 'golden', nameKey: 'skinGolden', cost: 1000000, colors: { head: '255, 220, 100', body: '255, 200, 0', alpha: 0.4, shadow: '#ffcc00', scanline: 'rgba(255, 200, 0, 0.05)' }, speedMult: 1 },
  { id: 'glitch', nameKey: 'skinGlitch', cost: 5000000, colors: { head: '0, 255, 0', body: '255, 0, 0', alpha: 0.5, shadow: '#ff0000', scanline: 'rgba(255, 0, 0, 0.06)' }, speedMult: 2 },
];

const PRESTIGE_SHOP_DEFS = [
  { id: 'autoBuy', costBase: 5, maxLevel: 1, effectLabel: '⟳ AUTO-BUY', descKey: 'shopAutoBuy' },
  { id: 'clickBoost', costBase: 2, maxLevel: 10, effectLabel: '+25% CLICK/lvl', descKey: 'shopClickBoost' },
  { id: 'dpsBoost', costBase: 2, maxLevel: 10, effectLabel: '+25% DPS/lvl', descKey: 'shopDpsBoost' },
  { id: 'startData', costBase: 3, maxLevel: 5, effectLabel: '+1K DATA START/lvl', descKey: 'shopStartData' },
  { id: 'comboBoost', costBase: 3, maxLevel: 5, effectLabel: '+0.05 COMBO/lvl', descKey: 'shopComboBoost' },
  { id: 'critBoost', costBase: 4, maxLevel: 5, effectLabel: '+5% CRIT/lvl', descKey: 'shopCritBoost' },
];

const EVENT_DEFS = [
  { id: 'data_leak', dur: 30, chance: 0.25, descKey: 'eventLeak', icon: '⚠' },
  { id: 'crypto_crash', dur: 60, chance: 0.25, descKey: 'eventCrash', icon: '📉' },
  { id: 'overclock', dur: 15, chance: 0.2, descKey: 'eventOverclock', icon: '⚡' },
  { id: 'windfall', dur: 0, chance: 0.15, descKey: 'eventWindfall', icon: '💰' },
  { id: 'ddos_attack', dur: 30, chance: 0.15, descKey: 'eventDdos', icon: '🔥' },
];

const ACHIEVEMENT_SKIN_REWARDS = {
  data_lord: 'golden',
  elite_hacker: 'neon',
  auto_pilot: 'hacker',
  completionist: 'glitch',
};

const TYPEVENT_DEFS = [
  { id: 'sql_inject', dur: 8, rewardMult: 10, penaltyMult: 0, descKey: 'sqlInjectWord' },
  { id: 'brute_force', dur: 5, rewardMult: 8, penaltyMult: 0.1, descKey: 'bruteForceKey' },
  { id: 'decode', dur: 10, rewardMult: 15, penaltyMult: 0, descKey: 'decodePrompt' },
  { id: 'command_chain', dur: 8, rewardMult: 12, penaltyMult: 0, descKey: 'commandChainPrompt' },
  { id: 'captcha', dur: 6, rewardMult: 6, penaltyMult: 0, descKey: 'captchaPrompt' },
];

const BOSS_VARIANTS = ['normal', 'shield', 'regen', 'counter'];
const BOSS_SHIELD_CLICKS_BASE = 3;
const BOSS_REGEN_INTERVAL_MS = 3000;
const BOSS_REGEN_PERCENT = 0.1;
const BOSS_COUNTER_INTERVAL_MS = 4000;
const BOSS_COUNTER_PENALTY = 0.03;

const TUTORIAL_STEPS = 5;

const SYNERGY_DEFS = [
  { id: 'scanner_cpu', nameKey: 'synergyScannerName', icon: '\u26A1', reqs: [{ id: 'scanner', lvl: 5 }, { id: 'cpu', lvl: 1 }] },
  { id: 'architect', nameKey: 'synergyArchName', icon: '\u25C6', reqs: [] },
  { id: 'overdrive_grid', nameKey: 'synergyOverdriveName', icon: '\u23E9', reqs: [{ id: 'overdrive', lvl: 1 }, { id: 'grid', lvl: 1 }] },
  { id: 'cipher_keymaker', nameKey: 'synergyCipherName', icon: '\u2726', reqs: [{ id: 'cipher', lvl: 1 }, { id: 'keymaker', lvl: 1 }] },
  { id: 'combo_master', nameKey: 'synergyComboName', icon: '\u2605', reqs: [{ id: 'rhythm', lvl: 5 }, { id: 'flow', lvl: 5 }, { id: 'momentum', lvl: 5 }, { id: 'adrenaline', lvl: 5 }] },
  { id: 'meta_stack', nameKey: 'synergyMetaName', icon: '\u229E', reqs: [{ id: 'backdoor', lvl: 3 }, { id: 'wormhole', lvl: 3 }, { id: 'turbo', lvl: 3 }, { id: 'nexus', lvl: 3 }] },
];

const SAVE_KEY = 'matrixHackerClicker';
const SAVE_INTERVAL = 15000;

